/* Mashrek MUN '26 — interactions only.
   All page content is static HTML generated by build.py; this file just
   powers the mobile menu, the Committees dropdown, the study-guide
   contents highlight and the fade-in on scroll. */
(function () {
  "use strict";

  var body = document.body;
  var header = document.querySelector(".site-header");
  var menuBtn = document.querySelector(".menu-btn");
  var dd = document.querySelector(".has-dropdown");
  var ddToggle = dd && dd.querySelector(".nav-toggle");

  /* ---------- Mobile menu ---------- */
  function setMenu(open) {
    body.classList.toggle("menu-open", open);
    menuBtn.setAttribute("aria-expanded", String(open));
    if (open) {
      // Place the panel directly under the header wherever the page is scrolled.
      var bottom = header.getBoundingClientRect().bottom;
      document.documentElement.style.setProperty("--nav-top", bottom + "px");
    }
  }
  if (menuBtn) {
    menuBtn.addEventListener("click", function () {
      setMenu(!body.classList.contains("menu-open"));
    });
    window.addEventListener("resize", function () {
      if (window.innerWidth > 980 && body.classList.contains("menu-open")) setMenu(false);
    });
  }

  /* ---------- Committees dropdown ---------- */
  function setDropdown(open) {
    if (!dd) return;
    dd.classList.toggle("open", open);
    ddToggle.setAttribute("aria-expanded", String(open));
  }
  if (dd) {
    ddToggle.addEventListener("click", function (e) {
      e.stopPropagation();
      setDropdown(!dd.classList.contains("open"));
    });
    document.addEventListener("click", function (e) {
      if (!dd.contains(e.target)) setDropdown(false);
    });
  }

  document.addEventListener("keydown", function (e) {
    if (e.key !== "Escape") return;
    if (dd && dd.classList.contains("open")) { setDropdown(false); ddToggle.focus(); }
    if (body.classList.contains("menu-open")) { setMenu(false); menuBtn.focus(); }
  });

  // Close the mobile menu after following an in-page link.
  document.querySelectorAll(".nav a").forEach(function (a) {
    a.addEventListener("click", function () { setMenu(false); setDropdown(false); });
  });

  var hasIO = "IntersectionObserver" in window;

  /* ---------- Study-guide contents highlight ---------- */
  var tocLinks = Array.prototype.slice.call(document.querySelectorAll(".toc a[href^='#']"));
  if (tocLinks.length && hasIO) {
    var byId = {};
    tocLinks.forEach(function (a) { byId[a.getAttribute("href").slice(1)] = a; });
    var spy = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        tocLinks.forEach(function (l) { l.classList.remove("current"); });
        var a = byId[entry.target.id];
        if (a) a.classList.add("current");
      });
    }, { rootMargin: "-20% 0px -70% 0px" });
    Object.keys(byId).forEach(function (id) {
      var el = document.getElementById(id);
      if (el) spy.observe(el);
    });
  }

  var reduceMotion = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  /* ---------- Split headings into words for the rise-in effect ---------- */
  document.querySelectorAll(".split").forEach(function (el) {
    var i = 0;
    (function walk(node) {
      Array.prototype.slice.call(node.childNodes).forEach(function (child) {
        if (child.nodeType === 3) {
          var frag = document.createDocumentFragment();
          child.textContent.split(/(\s+)/).forEach(function (part) {
            if (!part) return;
            if (/^\s+$/.test(part)) { frag.appendChild(document.createTextNode(part)); return; }
            var w = document.createElement("span"); w.className = "w";
            var inner = document.createElement("span"); inner.textContent = part;
            inner.style.setProperty("--i", i++);
            w.appendChild(inner); frag.appendChild(w);
          });
          child.parentNode.replaceChild(frag, child);
        } else if (child.nodeType === 1 && child.tagName !== "BR") {
          walk(child);
        }
      });
    })(el);
    el.setAttribute("aria-label", el.textContent.replace(/\s+/g, " ").trim());
  });

  /* ---------- Stagger indices ---------- */
  document.querySelectorAll("[data-stagger]").forEach(function (group) {
    Array.prototype.forEach.call(group.children, function (c, i) { c.style.setProperty("--i", i); });
  });

  /* ---------- Reveal on scroll ---------- */
  var reveals = document.querySelectorAll(".reveal, .split, [data-stagger], hr.rule, .double-rule, .unveil, .p-track");
  if (!hasIO) {
    reveals.forEach(function (el) { el.classList.add("in"); });
  } else {
    var ro = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) { entry.target.classList.add("in"); ro.unobserve(entry.target); }
      });
    }, { threshold: 0.08, rootMargin: "0px 0px -40px 0px" });
    reveals.forEach(function (el) {
      // Anything already on screen at load animates in straight away.
      if (el.getBoundingClientRect().top < window.innerHeight) {
        requestAnimationFrame(function () { el.classList.add("in"); });
      } else {
        ro.observe(el);
      }
    });
  }

  /* ---------- Header state, scroll progress, hero fade ---------- */
  // Header: an IntersectionObserver on a tiny marker at the top of the page (no scroll listener).
  var marker = document.createElement("div");
  marker.setAttribute("aria-hidden", "true");
  marker.style.cssText = "position:absolute;top:0;left:0;width:1px;height:24px;pointer-events:none";
  body.prepend(marker);
  if (hasIO && header) {
    new IntersectionObserver(function (e) {
      header.classList.toggle("scrolled", !e[0].isIntersecting);
    }).observe(marker);
  } else if (header) {
    header.classList.add("scrolled");
  }

  var bar = document.createElement("div");
  bar.className = "scroll-progress";
  bar.setAttribute("aria-hidden", "true");
  body.appendChild(bar);
  var heroInner = document.querySelector("[data-parallax]");

  var nativeScroll = window.CSS && CSS.supports && CSS.supports("animation-timeline: scroll()");
  if (nativeScroll) {
    // The browser drives both effects itself (see the @supports block in style.css).
    bar.classList.add("native");
    if (heroInner) heroInner.classList.add("native");
  } else if (!reduceMotion) {
    // Fallback for browsers without scroll-driven animations: one passive, frame-throttled listener.
    var ticking = false;
    var onScroll = function () {
      var max = document.documentElement.scrollHeight - window.innerHeight;
      bar.style.transform = "scaleX(" + (max > 0 ? Math.min(1, window.scrollY / max) : 0) + ")";
      if (heroInner && window.innerWidth > 700) {
        var y = Math.min(window.scrollY, 700);
        heroInner.style.transform = "translateY(" + (y * 0.28) + "px)";
        heroInner.style.opacity = String(Math.max(0, 1 - y / 620));
      }
      ticking = false;
    };
    window.addEventListener("scroll", function () {
      if (!ticking) { ticking = true; requestAnimationFrame(onScroll); }
    }, { passive: true });
    onScroll();
  }

  /* ---------- Save study guide as a PDF download ---------- */
  var pdfLib = null;
  function loadPdfLib() {
    if (window.html2pdf) return Promise.resolve();
    if (pdfLib) return pdfLib;
    pdfLib = new Promise(function (resolve, reject) {
      var s = document.createElement("script");
      s.src = "https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js";
      s.onload = resolve;
      s.onerror = function () { pdfLib = null; reject(new Error("html2pdf failed to load")); };
      document.head.appendChild(s);
    });
    return pdfLib;
  }
  document.querySelectorAll("[data-print]").forEach(function (btn) {
    btn.hidden = false;
    var label = btn.textContent;
    btn.addEventListener("click", function () {
      if (btn.disabled) return;
      var guide = document.querySelector("article.guide");
      var h1 = document.querySelector("h1");
      if (!guide || !h1) { window.print(); return; }
      btn.disabled = true;
      btn.textContent = "Preparing PDF\u2026";
      var box = null;
      function done() { if (box) box.remove(); btn.disabled = false; btn.textContent = label; }
      loadPdfLib().then(function () {
        var lede = document.querySelector(".lede");
        var brand = document.querySelector(".footer-brand strong");
        box = document.createElement("div");
        box.className = "pdf-export";
        var site = document.createElement("p");
        site.className = "pdf-site";
        site.textContent = brand ? brand.textContent : document.title;
        var title = document.createElement("h1");
        title.textContent = h1.textContent;
        box.appendChild(site);
        box.appendChild(title);
        if (lede) { var l = document.createElement("p"); l.className = "lede"; l.textContent = lede.textContent; box.appendChild(l); }
        box.appendChild(guide.cloneNode(true));
        document.body.appendChild(box);
        var page = location.pathname.split("/").pop().replace(/\.html$/, "") || "guide";
        return window.html2pdf().set({
          margin: 14,
          filename: page + "-study-guide.pdf",
          image: { type: "jpeg", quality: 0.95 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
          pagebreak: { mode: ["css", "legacy"], avoid: ["h2", "h3", "h4", "p", "li"] }
        }).from(box).save();
      }).then(done, function () { done(); window.print(); });
    });
  });

  /* ---------- Back-to-top button: shown once the page header is out of view ---------- */
  var toTop = document.querySelector(".to-top");
  var topSection = document.querySelector(".hero, .page-head");
  if (toTop && topSection && hasIO) {
    new IntersectionObserver(function (e) {
      toTop.classList.toggle("show", !e[0].isIntersecting);
    }).observe(topSection);
  }

  /* ---------- Count-up numbers ---------- */
  var counters = document.querySelectorAll("[data-count]");
  if (counters.length && hasIO && !reduceMotion) {
    var co = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        var el = entry.target, end = +el.getAttribute("data-count"), t0 = null;
        co.unobserve(el);
        el.textContent = "0";
        (function tick(t) {
          if (!t0) t0 = t;
          var k = Math.min(1, (t - t0) / 1400), e = 1 - Math.pow(1 - k, 4);
          el.textContent = String(Math.round(end * e));
          if (k < 1) requestAnimationFrame(tick);
        })(performance.now());
      });
    }, { threshold: 0.6 });
    counters.forEach(function (el) { co.observe(el); });
  }

  /* ---------- Hero canvas: rotating dotted globe + stars ---------- */
  var canvas = document.querySelector(".hero-canvas");
  var toggle = document.querySelector(".motion-toggle");
  if (canvas && canvas.getContext) {
    var ctx = canvas.getContext("2d");
    var W = 0, H = 0, dpr = 1, running = !reduceMotion, visible = true, raf = 0, rot = 0, last = 0;
    var tx = 0, ty = 0, px = 0, py = 0;     // pointer target / eased pointer (-0.5 .. 0.5)
    if (!reduceMotion && window.matchMedia("(pointer: fine)").matches) {
      window.addEventListener("pointermove", function (e) {
        tx = e.clientX / window.innerWidth - 0.5; ty = e.clientY / window.innerHeight - 0.5;
      }, { passive: true });
    }
    var N = 1100, pts = [], stars = [];
    var golden = Math.PI * (3 - Math.sqrt(5));
    for (var k = 0; k < N; k++) {           // Fibonacci sphere
      var yk = 1 - (k / (N - 1)) * 2, r = Math.sqrt(1 - yk * yk), th = golden * k;
      pts.push([Math.cos(th) * r, yk, Math.sin(th) * r]);
    }
    for (var s2 = 0; s2 < 140; s2++) {
      stars.push({ x: Math.random(), y: Math.random(), r: Math.random() * 1.3 + .3, p: Math.random() * 6.28, sp: .4 + Math.random() * 1.2 });
    }
    function resize() {
      dpr = Math.min(window.devicePixelRatio || 1, 1.5);
      W = canvas.clientWidth; H = canvas.clientHeight;
      canvas.width = W * dpr; canvas.height = H * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      draw(0);
    }
    function draw(t) {
      ctx.clearRect(0, 0, W, H);
      // stars
      for (var i = 0; i < stars.length; i++) {
        var st = stars[i], a = .25 + .55 * (0.5 + 0.5 * Math.sin(st.p + t * 0.001 * st.sp));
        ctx.fillStyle = "rgba(255,255,255," + a.toFixed(3) + ")";
        ctx.fillRect(st.x * W, st.y * H, st.r * 1.6, st.r * 1.6);
      }
      // globe
      var R = Math.min(W, H) * (W < 700 ? .6 : .44), cx = W / 2 + px * 26, cy = H * .46 + py * 18;
      var tilt = -0.38 + py * 0.32, rr = rot + px * 0.7;
      var ct = Math.cos(tilt), sn = Math.sin(tilt), cr = Math.cos(rr), sr = Math.sin(rr);
      var halo = ctx.createRadialGradient(cx, cy, R * .2, cx, cy, R * 1.25);
      halo.addColorStop(0, "rgba(120,150,220,.10)"); halo.addColorStop(1, "rgba(120,150,220,0)");
      ctx.fillStyle = halo; ctx.beginPath(); ctx.arc(cx, cy, R * 1.25, 0, 6.283); ctx.fill();
      for (var j = 0; j < N; j++) {
        var p = pts[j];
        var x = p[0] * cr + p[2] * sr, z = -p[0] * sr + p[2] * cr, y = p[1];
        var y2 = y * ct - z * sn, z2 = y * sn + z * ct;
        if (z2 < -0.15) continue;
        var alpha = 0.10 + 0.72 * Math.max(0, z2);
        ctx.fillStyle = "rgba(196,210,240," + alpha.toFixed(3) + ")";
        var size = 1 + 1.7 * Math.max(0, z2);
        ctx.fillRect(cx + x * R - size / 2, cy + y2 * R - size / 2, size, size);
      }
      ctx.strokeStyle = "rgba(196,210,240,.16)"; ctx.lineWidth = 1;
      ctx.beginPath(); ctx.arc(cx, cy, R, 0, 6.283); ctx.stroke();
      ctx.strokeStyle = "rgba(196,210,240,.07)";
      ctx.beginPath(); ctx.arc(cx, cy, R * 1.12, 0, 6.283); ctx.stroke();
    }
    function frame(t) {
      if (!last) last = t;
      rot += (t - last) * 0.00008; last = t;
      px += (tx - px) * 0.045; py += (ty - py) * 0.045;
      draw(t);
      raf = running && visible ? requestAnimationFrame(frame) : 0;
    }
    function start() { if (!raf && running && visible) { last = 0; raf = requestAnimationFrame(frame); } }
    function stop() { if (raf) cancelAnimationFrame(raf); raf = 0; }
    window.addEventListener("resize", resize);
    resize();
    // Let the opening curtain run on its own; start the globe once it has gone.
    var introActive = document.documentElement.classList.contains("intro");
    var begin = function () {
      introActive = false;
      if (hasIO) new IntersectionObserver(function (e) { visible = e[0].isIntersecting; visible ? start() : stop(); }).observe(canvas);
      start();
    };
    if (introActive) {
      var mo = new MutationObserver(function () {
        if (!document.documentElement.classList.contains("intro")) { mo.disconnect(); begin(); }
      });
      mo.observe(document.documentElement, { attributes: true, attributeFilter: ["class"] });
    } else { begin(); }

    if (toggle) {
      var setPaused = function (paused) {
        running = !paused;
        body.classList.toggle("motion-paused", paused);
        toggle.setAttribute("aria-pressed", String(paused));
        toggle.querySelector(".label").textContent = paused ? "Play motion" : "Pause motion";
        toggle.title = paused ? "Play motion" : "Pause motion";
        toggle.querySelector(".icon").textContent = paused ? "▶" : "❚❚";
        paused ? stop() : start();
      };
      if (reduceMotion) setPaused(true);
      toggle.addEventListener("click", function () { setPaused(running); });
    }
  }


  /* ---------- Magnetic buttons (desktop pointer only) ---------- */
  if (!reduceMotion && window.matchMedia("(hover: hover) and (pointer: fine)").matches) {
    document.querySelectorAll(".btn").forEach(function (btn) {
      btn.classList.add("magnetic");
      btn.addEventListener("pointermove", function (e) {
        var r = btn.getBoundingClientRect();
        btn.style.setProperty("--mx", ((e.clientX - r.left - r.width / 2) * 0.18).toFixed(1) + "px");
        btn.style.setProperty("--my", ((e.clientY - r.top - r.height / 2) * 0.28).toFixed(1) + "px");
      });
      btn.addEventListener("pointerleave", function () {
        btn.style.setProperty("--mx", "0px"); btn.style.setProperty("--my", "0px");
      });
    });
  }

  /* ---------- Glossary placards: tap to reveal the meaning ---------- */
  document.querySelectorAll(".g-terms li").forEach(function (li) {
    var btn = li.querySelector(".term"), def = li.querySelector(".t-def");
    var toggle = function () {
      var open = !li.classList.contains("open");
      li.classList.toggle("open", open);
      btn.setAttribute("aria-expanded", String(open));
    };
    btn.addEventListener("click", toggle);
    def.addEventListener("click", function () { toggle(); btn.focus(); });
  });

  /* ---------- Photo viewer ---------- */
  var openers = Array.prototype.slice.call(document.querySelectorAll(".g-open"));
  if (openers.length && window.HTMLDialogElement) {
    var dlg = document.createElement("dialog");
    dlg.className = "lightbox";
    dlg.setAttribute("aria-label", "Photo viewer");
    dlg.innerHTML = '<figure><img alt=""><figcaption></figcaption></figure>' +
      '<button class="lb-btn lb-close" type="button" aria-label="Close">✕</button>' +
      '<button class="lb-btn lb-prev" type="button" aria-label="Previous photo">←</button>' +
      '<button class="lb-btn lb-next" type="button" aria-label="Next photo">→</button>';
    document.body.appendChild(dlg);
    var lbImg = dlg.querySelector("img"), lbCap = dlg.querySelector("figcaption"), current = 0;
    var show = function (i) {
      current = (i + openers.length) % openers.length;
      var img = openers[current].querySelector("img");
      var cap = openers[current].parentNode.querySelector("figcaption");
      lbImg.src = img.currentSrc && img.currentSrc.indexOf("-900") === -1 ? img.currentSrc : img.src;
      lbImg.alt = img.alt;
      lbCap.textContent = cap ? cap.textContent : "";
    };
    openers.forEach(function (btn, i) {
      btn.addEventListener("click", function () { show(i); dlg.showModal(); });
    });
    dlg.querySelector(".lb-close").addEventListener("click", function () { dlg.close(); });
    dlg.querySelector(".lb-prev").addEventListener("click", function () { show(current - 1); });
    dlg.querySelector(".lb-next").addEventListener("click", function () { show(current + 1); });
    dlg.addEventListener("click", function (e) { if (e.target === dlg) dlg.close(); });
    dlg.addEventListener("keydown", function (e) {
      if (e.key === "ArrowLeft") show(current - 1);
      if (e.key === "ArrowRight") show(current + 1);
    });
    dlg.addEventListener("close", function () { openers[current].focus(); });
  }

  /* ---------- Theme film: plays while on screen, pauses when scrolled past ---------- */
  document.querySelectorAll(".film-screen").forEach(function (screen) {
    var video = screen.querySelector("video");
    if (!video) return;
    var soundBtn = screen.querySelector(".film-sound");
    var pauseBtn = screen.querySelector(".film-pause");
    var slider = screen.querySelector(".film-volume");
    var inView = false;
    var userPaused = false;                // set when the visitor presses Pause

    video.removeAttribute("controls");     // our two buttons replace the native bar
    video.muted = true;
    video.defaultMuted = true;             // Safari needs this set for muted autoplay
    video.pause();
    screen.classList.add("enhanced");

    function sync() {
      var paused = video.paused;
      pauseBtn.setAttribute("aria-pressed", String(userPaused));
      pauseBtn.querySelector(".lbl").textContent = userPaused ? "Play" : "Pause";
      pauseBtn.querySelector(".ic").textContent = userPaused ? "▶" : "❚❚";
      soundBtn.setAttribute("aria-pressed", String(!video.muted));
      soundBtn.querySelector(".lbl").textContent = video.muted ? "Turn On Sound" : "Mute";
      if (slider) slider.value = video.muted ? 0 : video.volume;
    }

    // Safari in Low Power Mode refuses to autoplay <video>, even muted. Safari can still
    // show the same MP4 as an animated <img>, which keeps playing, so we switch to that
    // silent stand-in until the visitor asks for sound (a tap always allows playback).
    var imgMode = false, imgTried = false, bar = screen.querySelector(".film-bar");
    function useImageFallback() {
      if (imgTried) return; imgTried = true;
      var src = video.currentSrc || (video.querySelector("source") || {}).src;
      if (!src) return;
      var img = new Image();
      img.className = "film-img"; img.alt = ""; img.setAttribute("aria-hidden", "true"); img.decoding = "async";
      img.onload = function () {            // only Safari can decode an MP4 inside <img>
        imgMode = true;
        screen.insertBefore(img, bar);
        screen.classList.add("img-mode");
        update();
      };
      img.src = src;
    }

    // Other browsers that block autoplay: start on the first tap, click or key press.
    var unlockEvents = ["pointerdown", "touchstart", "keydown"];
    function unlock() {
      unlockEvents.forEach(function (ev) { document.removeEventListener(ev, unlock, true); });
      if (!imgMode && inView && !userPaused && video.paused) play();
    }
    function play() {
      var p = video.play();
      if (p && p.catch) p.catch(function (err) {
        if (err && err.name === "NotAllowedError") useImageFallback();
        unlockEvents.forEach(function (ev) { document.addEventListener(ev, unlock, { capture: true, passive: true }); });
      });
    }
    function update() {
      var shouldPlay = inView && !userPaused;
      if (imgMode) { video.pause(); screen.classList.toggle("img-paused", !shouldPlay); return; }
      if (shouldPlay) play(); else video.pause();
    }

    if (hasIO) {
      new IntersectionObserver(function (e) {
        inView = e[0].isIntersecting; update();
      }, { threshold: 0.35 }).observe(screen);
    } else { inView = true; update(); }

    document.addEventListener("visibilitychange", function () {
      if (!document.hidden) update();
    });

    pauseBtn.addEventListener("click", function () {
      userPaused = !userPaused;
      update(); sync();
    });
    soundBtn.addEventListener("click", function () {
      if (imgMode) {                         // leave the silent stand-in for the real film
        imgMode = false;
        screen.classList.remove("img-mode", "img-paused");
      }
      video.muted = !video.muted;
      if (!video.muted && !video.dataset.restarted) { video.currentTime = 0; video.dataset.restarted = "1"; }
      if (!video.muted) { userPaused = false; update(); }
      sync();
    });
    if (slider) slider.addEventListener("input", function () {
      var v = parseFloat(slider.value);
      video.volume = v;
      if (v > 0 && video.muted) soundBtn.click();
      else if (v === 0 && !video.muted) video.muted = true;
    });
    ["play", "pause", "volumechange"].forEach(function (ev) { video.addEventListener(ev, sync); });
    sync();
  });
})();
